### ISSUE TITLE
RuntimeError: instance.__dict__ not accessible in restricted mode

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#358]
**Reported by anonymous on 16 Nov 2015 11:09 UTC**
#### How to Reproduce

While doing a GET operation on `/browser/branches/public/CrossCheck_Results/FMI_2.0/CoSimulation/win32/Silver/3.2/Silver/3.2/Compute/passed`, Trac issued an internal error.

_(please provide additional details here)_

Request parameters:
```
{'path': u'/branches/public/CrossCheck_Results/FMI_2.0/CoSimulation/win32/Silver/3.2/Silver/3.2/Compute/failed'}
```

User agent: `Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; rv:11.0) like Gecko`

#### System Information
_System information not available_

#### Enabled Plugins
_Plugin information not available_

#### Python Traceback
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/trac/web/main.py", line 554, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/local/lib/python2.6/dist-packages/trac/web/main.py", line 247, in dispatch
    resp = chosen_handler.process_request(req)
  File "/usr/local/lib/python2.6/dist-packages/trac/versioncontrol/web_ui/browser.py", line 345, in process_request
    reponame, repos, path = rm.get_repository_by_path(path)
  File "/usr/local/lib/python2.6/dist-packages/trac/versioncontrol/api.py", line 628, in get_repository_by_path
    return (reponame, self.get_repository(reponame),
  File "/usr/local/lib/python2.6/dist-packages/trac/versioncontrol/api.py", line 604, in get_repository
    repoinfo.copy())
  File "/usr/local/lib/python2.6/dist-packages/tracopt/versioncontrol/svn/svn_fs.py", line 335, in get_repository
    repos = SubversionRepository(dir, params, self.log)
  File "/usr/local/lib/python2.6/dist-packages/tracopt/versioncontrol/svn/svn_fs.py", line 348, in __init__
    self.pool = Pool()
  File "/usr/local/lib/python2.6/dist-packages/tracopt/versioncontrol/svn/svn_fs.py", line 170, in __init__
    self._pool = core.svn_pool_create(self._parent_pool())
  File "/usr/lib/python2.6/dist-packages/svn/core.py", line 305, in svn_pool_create
    return Pool(parent_pool)
  File "/usr/lib/python2.6/dist-packages/libsvn/core.py", line 1628, in svn_pool_create
    return _core.svn_pool_create(*args)
  File "/usr/lib/python2.6/dist-packages/libsvn/core.py", line 6794, in _wrap
    obj.set_parent_pool(self)
  File "/usr/lib/python2.6/dist-packages/libsvn/core.py", line 6707, in set_parent_pool
    self._parent_pool = parent_pool or application_pool
  File "/usr/lib/python2.6/dist-packages/libsvn/core.py", line 6695, in <lambda>
    __setattr__ = lambda self, name, value: _swig_setattr(self, apr_pool_t, name, value)
  File "/usr/lib/python2.6/dist-packages/libsvn/core.py", line 44, in _swig_setattr
    return _swig_setattr_nondynamic(self,class_type,name,value,0)
  File "/usr/lib/python2.6/dist-packages/libsvn/core.py", line 39, in _swig_setattr_nondynamic
    self.__dict__[name] = value
RuntimeError: instance.__dict__ not accessible in restricted mode
```

----

Migrated-From: https://trac.fmi-standard.org/ticket/358

**Comment by modelica-trac-importer** [comment]
**Comment by andreas&#46;junghanns on 6 Feb 2017 10:44 UTC**
Please reopen if after fixing the path this still fails.
