### ISSUE TITLE
MemoryError:

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#421]
**Reported by anonymous on 13 Jun 2017 06:30 UTC**
#### How to Reproduce

While doing a GET operation on `/browser/branches/public`, Trac issued an internal error.

_Page is not responding for download_

Request parameters:
```
{u'format': u'zip', 'path': u'/branches/public', u'rev': u'3715'}
```

User agent: `Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0`

#### System Information
_System information not available_

#### Enabled Plugins
_Plugin information not available_

#### Interface Customization
_Interface customization information not available_

#### Python Traceback
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/trac/web/main.py", line 613, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/local/lib/python2.7/dist-packages/trac/web/main.py", line 253, in dispatch
    resp = chosen_handler.process_request(req)
  File "/usr/local/lib/python2.7/dist-packages/trac/versioncontrol/web_ui/browser.py", line 402, in process_request
    self._render_zip(req, context, repos, node, rev)
  File "/usr/local/lib/python2.7/dist-packages/trac/versioncontrol/web_ui/browser.py", line 659, in _render_zip
    render_zip(req, filename, repos, root_node, self._iter_nodes)
  File "/usr/local/lib/python2.7/dist-packages/trac/versioncontrol/web_ui/util.py", line 213, in render_zip
    data = node.get_processed_content(eol_hint='CRLF').read()
  File "/usr/local/lib/python2.7/dist-packages/tracopt/versioncontrol/svn/svn_fs.py", line 1202, in read
    return self._read_dumb(self.stream, n)
  File "/usr/local/lib/python2.7/dist-packages/tracopt/versioncontrol/svn/svn_fs.py", line 1286, in _read_dumb
    return stream.read(n)
  File "/usr/lib/python2.7/dist-packages/svn/core.py", line 182, in read
    return ''.join(chunks)
MemoryError
```

----

Migrated-From: https://trac.fmi-standard.org/ticket/421

**Comment by modelica-trac-importer** [comment]
**Comment by cbertsch on 30 May 2018 19:06 UTC**
I do not understand this issue at all --> closing. Plesae re-open if someone understands it.
